version: '3.8'

services:
  db:
    image: mysql:8.0.33
    restart: always
    container_name: db-mysql
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'mysql'
      MYSQL_PASSWORD: 'mysql!'
      MYSQL_ROOT_PASSWORD: 'r@@tp@ssw0rd'
      TZ: Asia/Bangkok
    ports:
      - '3306:3306'
    volumes:
      - ./my-db:/var/lib/mysql
